/**
 * Auto-generated from AnimationPathTypes enum
 */
export const AnimationPathTypes: Record<number, string> = {
  '-1': 'None',
  0: 'Idle',
  1: 'Move',
  2: 'RandomizeAnimationSet',
  3: 'NukeStrike',
  4: 'MeleeStrike',
  5: 'MeleeHurt',
  6: 'MeleeDie',
  7: 'MeleeFortified',
  8: 'RangedStrike',
  9: 'RangedDie',
  10: 'RangedFortified',
  11: 'RangedRunhit',
  12: 'RangedRundie',
  13: 'LeaderCommand',
  14: 'Airfadein',
  15: 'Airfadeout',
  16: 'Airstrike',
  17: 'Airbomb',
  18: 'Heal',
  19: 'Sleep',
  20: 'Fortify',
  21: 'MeleeFortify',
  22: 'Pillage',
  23: 'Sentry',
  24: 'Found',
  25: 'Irrigate',
  26: 'Build',
  27: 'Mine',
  28: 'Chop',
  29: 'Shovel',
  30: 'Railroad',
  31: 'GreatEvent',
  32: 'Surrender',
  33: 'Airpatrol'
};
