/**
 * Auto-generated from AnimationPathTypes enum
 */
export const AnimationPathTypes: Record<number, string> = {
  '-1': 'None',
  0: 'Idle',
  1: 'Move',
  2: 'Damage',
  3: 'RandomizeAnimationSet',
  4: 'NukeStrike',
  5: 'MeleeStrike',
  6: 'MeleeHurt',
  7: 'MeleeDie',
  8: 'MeleeFortified',
  9: 'MeleeDieFade',
  10: 'MeleeFlee',
  11: 'RangedStrike',
  12: 'RangedDie',
  13: 'RangedFortified',
  14: 'RangedRunhit',
  15: 'RangedRundie',
  16: 'RangedDieFade',
  17: 'LeaderCommand',
  18: 'Airfadein',
  19: 'Airfadeout',
  20: 'Airstrike',
  21: 'Airbomb',
  22: 'Heal',
  23: 'Sleep',
  24: 'Fortify',
  25: 'MeleeFortify',
  26: 'Pillage',
  27: 'Sentry',
  28: 'Found',
  29: 'Irrigate',
  30: 'Build',
  31: 'Mine',
  32: 'Chop',
  33: 'Shovel',
  34: 'Railroad',
  35: 'GreatEvent',
  36: 'Surrender',
  37: 'Airpatrol'
};
