/**
 * Auto-generated from ControlTypes enum
 */
export const ControlTypes: Record<number, string> = {
  '-1': 'None',
  0: 'Centeronselection',
  1: 'Selectyunittype',
  2: 'Selectyunitall',
  3: 'Selectcity',
  4: 'Selectcapital',
  5: 'Nextcity',
  6: 'Prevcity',
  7: 'Nextunit',
  8: 'Prevunit',
  9: 'Cycleunit',
  10: 'CycleunitAlt',
  11: 'Cycleworker',
  12: 'Lastunit',
  13: 'Endturn',
  14: 'EndturnAlt',
  15: 'Forceendturn',
  16: 'Automoves',
  17: 'Ping',
  18: 'Yields',
  19: 'ResourceAll',
  20: 'UnitIcons',
  21: 'Scores',
  22: 'LoadGame',
  23: 'OptionsScreen',
  24: 'Retire',
  25: 'SaveGroup',
  26: 'SaveNormal',
  27: 'QuickSave',
  28: 'QuickLoad',
  29: 'Civilopedia',
  30: 'PoliciesScreen',
  31: 'ForeignScreen',
  32: 'MilitaryScreen',
  33: 'TechChooser',
  34: 'TurnLog',
  35: 'DomesticScreen',
  36: 'VictoryScreen',
  37: 'Info',
  38: 'SelectHealthy',
  39: 'ToggleStrategicView',
  40: 'AdvisorCounsel',
  41: 'EspionageOverview',
  42: 'ReligionOverview',
  43: 'RestartGame',
  44: 'ToggleObserverMode',
  45: 'ToggleAiTakeover',
  46: 'SwitchToNextPlayer'
};
