/**
 * Auto-generated from DiploUIStateTypes enum
 */
export const DiploUIStateTypes: Record<number, string> = {
  '-1': 'None',
  0: 'DefaultRoot',
  1: 'WarDeclaredByHuman',
  2: 'PeaceMadeByHuman',
  3: 'Trade',
  4: 'TradeAiMakesOffer',
  5: 'TradeAiAcceptsOffer',
  6: 'TradeAiRejectsOffer',
  7: 'TradeAiMakesDemand',
  8: 'TradeAiMakesRequest',
  9: 'TradeHumanOffersConcessions',
  10: 'HumanDemand',
  11: 'BlankDiscussionReturnToRoot',
  12: 'BlankDiscussion',
  13: 'BlankDiscussionMeanHuman',
  14: 'BlankDiscussionMeanAi',
  15: 'AiDeclaredWar',
  16: 'DiscussHumanInvoked',
  17: 'DiscussAggressiveMilitaryWarning',
  18: 'DiscussIAttackedYourMinorCiv',
  19: 'DiscussIBulliedYourMinorCiv',
  20: 'DiscussYouAttackedMinorCiv',
  21: 'DiscussYouKilledMinorCiv',
  22: 'DiscussYouBulliedMinorCiv',
  23: 'DiscussProtectMinorCiv',
  24: 'DiscussYouExpansionSeriousWarning',
  25: 'DiscussYouExpansionWarning',
  26: 'DiscussYouPlotBuyingSeriousWarning',
  27: 'DiscussYouPlotBuyingWarning',
  28: 'DiscussWorkWithUs',
  29: 'DiscussWorkAgainstSomeone',
  30: 'DiscussCoopWar',
  31: 'DiscussCoopWarTime',
  32: 'DiscussPlanResearchAgreement',
  33: 'DiscussAiRequestDenounce',
  34: 'CaughtYourSpy',
  35: 'KilledYourSpy',
  36: 'KilledMySpy',
  37: 'ConfrontYouKilledMySpy',
  38: 'StopConversions',
  39: 'StopDigging',
  40: 'HumanRequest',
  41: 'TradeAiMakesGenerousOffer',
  42: 'DiscussAiRevokeVassalage',
  43: 'DiscussEndWorkWithUs'
};
