/**
 * Auto-generated from FromUIDiploEventTypes enum
 */
export const FromUIDiploEventTypes: Record<number, string> = {
  '-1': 'None',
  0: 'HumanDeclaresWar',
  1: 'HumanNegotiatePeace',
  2: 'HumanWantsDiscussion',
  3: 'HumanDiscussionDontSettle',
  4: 'HumanDiscussionWorkWithUs',
  5: 'HumanDiscussionEndWorkWithUs',
  6: 'DemandHumanRefusal',
  7: 'RequestHumanRefusal',
  8: 'AggressiveMilitaryWarningResponse',
  9: 'IAttackedYourMinorCivResponse',
  10: 'IBulliedYourMinorCivResponse',
  11: 'AttackedMinorResponse',
  12: 'KilledMinorResponse',
  13: 'BulliedMinorResponse',
  14: 'ExpansionSeriousWarningResponse',
  15: 'ExpansionWarningResponse',
  16: 'PlotBuyingSeriousWarningResponse',
  17: 'PlotBuyingWarningResponse',
  18: 'WorkWithUsResponse',
  19: 'WorkAgainstSomeoneResponse',
  20: 'Denounce',
  21: 'CoopWarOffer',
  22: 'CoopWarResponse',
  23: 'CoopWarNowResponse',
  24: 'HumanDemand',
  25: 'PlanRaResponse',
  26: 'AiRequestDenounceResponse',
  27: 'CaughtYourSpyResponse',
  28: 'KilledMySpyResponse',
  29: 'HumanDiscussionStopSpying',
  30: 'HumanDiscussionShareIntrigue',
  31: 'HumanDiscussionStopSpreadingReligion',
  32: 'StopConversions',
  33: 'HumanDiscussionStopDigging',
  34: 'StopDigging',
  35: 'HumanDiscussionShareOpinion',
  36: 'HumanRequest',
  37: 'HumanEndsVassalage',
  38: 'HumanMoveTroopsResponse',
  39: 'HumanEndWorkWithUsResponse',
  40: 'MeanResponse'
};
