// Auto-generated file - DO NOT EDIT
// Generated by generate-index.js

import { BarbariansCampCleared } from './BarbariansCampCleared.js';
import { BarbariansCampFounded } from './BarbariansCampFounded.js';
import { BarbariansSpawnedUnit } from './BarbariansSpawnedUnit.js';
import { BuildFinished } from './BuildFinished.js';
import { CapitalChanged } from './CapitalChanged.js';
import { ChangeGoldenAgeProgressMeter } from './ChangeGoldenAgeProgressMeter.js';
import { CircumnavigatedGlobe } from './CircumnavigatedGlobe.js';
import { CityBeginsWLTKD } from './CityBeginsWLTKD.js';
import { CityBoughtPlot } from './CityBoughtPlot.js';
import { CityCaptureComplete } from './CityCaptureComplete.js';
import { CityConstructed } from './CityConstructed.js';
import { CityConvertsPantheon } from './CityConvertsPantheon.js';
import { CityConvertsReligion } from './CityConvertsReligion.js';
import { CityCreated } from './CityCreated.js';
import { CityEndsWLTKD } from './CityEndsWLTKD.js';
import { CityEventActivated } from './CityEventActivated.js';
import { CityEventChoiceActivated } from './CityEventChoiceActivated.js';
import { CityEventChoiceEnded } from './CityEventChoiceEnded.js';
import { CityExtendsWLTKD } from './CityExtendsWLTKD.js';
import { CityFlipped } from './CityFlipped.js';
import { CityInvestedBuilding } from './CityInvestedBuilding.js';
import { CityInvestedUnit } from './CityInvestedUnit.js';
import { CityPrepared } from './CityPrepared.js';
import { CityProjectComplete } from './CityProjectComplete.js';

export const eventSchemas = {
  'BarbariansCampCleared': BarbariansCampCleared,
  'BarbariansCampFounded': BarbariansCampFounded,
  'BarbariansSpawnedUnit': BarbariansSpawnedUnit,
  'BuildFinished': BuildFinished,
  'CapitalChanged': CapitalChanged,
  'ChangeGoldenAgeProgressMeter': ChangeGoldenAgeProgressMeter,
  'CircumnavigatedGlobe': CircumnavigatedGlobe,
  'CityBeginsWLTKD': CityBeginsWLTKD,
  'CityBoughtPlot': CityBoughtPlot,
  'CityCaptureComplete': CityCaptureComplete,
  'CityConstructed': CityConstructed,
  'CityConvertsPantheon': CityConvertsPantheon,
  'CityConvertsReligion': CityConvertsReligion,
  'CityCreated': CityCreated,
  'CityEndsWLTKD': CityEndsWLTKD,
  'CityEventActivated': CityEventActivated,
  'CityEventChoiceActivated': CityEventChoiceActivated,
  'CityEventChoiceEnded': CityEventChoiceEnded,
  'CityExtendsWLTKD': CityExtendsWLTKD,
  'CityFlipped': CityFlipped,
  'CityInvestedBuilding': CityInvestedBuilding,
  'CityInvestedUnit': CityInvestedUnit,
  'CityPrepared': CityPrepared,
  'CityProjectComplete': CityProjectComplete,
};

export type EventName = keyof typeof eventSchemas;
