/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface LocalizedText {
  Gender: string | null;
  Language: string | null;
  Plurality: string | null;
  Tag: string | null;
  Text: string | null;
}

export interface DB {
  LocalizedText: LocalizedText;
}
