name: Update Prebuilt Binaries

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  push:
    paths:
      - 'civ5-dll'  # Trigger when submodule is updated

jobs:
  update-binaries:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get submodule commit
        id: submodule
        run: |
          SUBMODULE_COMMIT=$(git submodule status civ5-dll | awk '{print $1}' | sed 's/^[+-]//')
          echo "commit=$SUBMODULE_COMMIT" >> $GITHUB_OUTPUT
          echo "Submodule commit: $SUBMODULE_COMMIT"

      - name: Download Debug artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          repo: CIVITAS-John/vox-deorum
          workflow: build.yml
          workflow_conclusion: success
          commit: ${{ steps.submodule.outputs.commit }}
          name: VP_MSVC_Debug
          path: ./debug-artifact

      - name: Download Release artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          repo: CIVITAS-John/vox-deorum
          workflow: build.yml
          workflow_conclusion: success
          commit: ${{ steps.submodule.outputs.commit }}
          name: VP_MSVC_Release
          path: ./release-artifact

      - name: Update prebuilt binaries
        run: |
          # Update debug binaries
          if [ -d "./debug-artifact" ]; then
            echo "Updating debug binaries..."
            rm -rf scripts/debug/*
            cp -r ./debug-artifact/* scripts/debug/
          fi

          # Update release binaries
          if [ -d "./release-artifact" ]; then
            echo "Updating release binaries..."
            rm -rf scripts/release/*
            cp -r ./release-artifact/* scripts/release/
          fi

      - name: Check for changes
        id: changes
        run: |
          git add scripts/debug scripts/release
          if git diff --staged --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Changes detected in binaries"
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Update prebuilt binaries from civ5-dll ${{ steps.submodule.outputs.commit }}"
          title: "Update prebuilt binaries from civ5-dll"
          body: |
            This PR updates the prebuilt binaries from the civ5-dll submodule.

            - Submodule commit: `${{ steps.submodule.outputs.commit }}`
            - Debug artifact: VP_MSVC_Debug
            - Release artifact: VP_MSVC_Release

            Auto-generated by GitHub Actions.
          branch: update-prebuilt-binaries
          delete-branch: true
          labels: |
            dependencies
            automated